(() => {
  "use strict";
  const KEY="soma-budget-planner-v2", OLD="soma-budget-planner-v1", THEME_KEY="soma-budget-theme";
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
  const now=()=>new Date().toISOString().slice(0,7), uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
  const amount=v=>Math.max(0,Number.isFinite(Number(v))?Number(v):0);
  const label=m=>new Intl.DateTimeFormat("en-US",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${m}-01T00:00:00Z`));
  const inferredType=name=>/housing|rent|mortgage|utilities|insurance|debt|subscription/i.test(name||"")?"fixed":"flexible";
  const sample=(month=now())=>({month,income:8500,categories:[
    {id:uid(),name:"Housing",type:"fixed",items:[{id:uid(),name:"Rent (SOMA 1BR)",budget:3500,actual:3500},{id:uid(),name:"Renter's Insurance",budget:25,actual:25}]},
    {id:uid(),name:"Utilities",type:"fixed",items:[{id:uid(),name:"PG&E",budget:120,actual:0},{id:uid(),name:"Internet & Phone",budget:165,actual:0},{id:uid(),name:"Water & Garbage",budget:60,actual:0}]},
    {id:uid(),name:"Food & Pet Care",type:"flexible",items:[{id:uid(),name:"Groceries",budget:450,actual:0},{id:uid(),name:"Dining Out & Coffee",budget:350,actual:0},{id:uid(),name:"Pet Care (Diggy)",budget:100,actual:0}]},
    {id:uid(),name:"Lifestyle & Transit",type:"flexible",items:[{id:uid(),name:"Entertainment & Nightlife",budget:300,actual:0},{id:uid(),name:"Transit & Rideshare",budget:150,actual:0},{id:uid(),name:"Subscriptions",budget:100,actual:0}]}
  ]});
  const clean=(b,month=now())=>({month:/^\d{4}-\d{2}$/.test(b?.month||"")?b.month:month,income:amount(b?.income),categories:Array.isArray(b?.categories)?b.categories.slice(0,100).map(c=>({id:String(c?.id||uid()),name:String(c?.name||"Untitled category").slice(0,50),type:c?.type==="fixed"?"fixed":c?.type==="flexible"?"flexible":inferredType(c?.name),items:Array.isArray(c?.items)?c.items.slice(0,200).map(i=>({id:String(i?.id||uid()),name:String(i?.name||"Untitled item").slice(0,70),budget:amount(i?.budget),actual:amount(i?.actual)})):[]})):[]});
  const clone=(b,month)=>({month,income:b.income,categories:b.categories.map(c=>({id:uid(),name:c.name,type:c.type,items:c.items.map(i=>({id:uid(),name:i.name,budget:i.budget,actual:0}))}))});
  const normalize=data=>{if(!data||data.version!==2||!data.months||typeof data.months!=="object"||Array.isArray(data.months))throw Error();const entries=Object.entries(data.months).filter(([m])=>/^\d{4}-\d{2}$/.test(m)).slice(0,240);if(!entries.length)throw Error();const months=Object.fromEntries(entries.map(([m,b])=>[m,clean(b,m)])),activeMonth=months[data.activeMonth]?data.activeMonth:Object.keys(months).sort().at(-1);return{version:2,activeMonth,months}};
  const load=()=>{try{return normalize(JSON.parse(localStorage.getItem(KEY)))}catch{}try{const old=JSON.parse(localStorage.getItem(OLD));if(old?.categories){const b=clean(old);return{version:2,activeMonth:b.month,months:{[b.month]:b}}}}catch{}const b=sample();return{version:2,activeMonth:b.month,months:{[b.month]:b}}};
  let store=load(),timer; const active=()=>store.months[store.activeMonth];
  const catTotals=c=>({planned:c.items.reduce((s,i)=>s+amount(i.budget),0),actual:c.items.reduce((s,i)=>s+amount(i.actual),0)});
  const totals=(b=active())=>{const groups=b.categories.map(catTotals),planned=groups.reduce((s,g)=>s+g.planned,0),actual=groups.reduce((s,g)=>s+g.actual,0);return{planned,actual,remaining:b.income-actual,plannedBalance:b.income-planned,spentRate:planned?actual/planned*100:0}};
  const save=()=>{$("#saveStatus").textContent="Saving...";clearTimeout(timer);timer=setTimeout(()=>{localStorage.setItem(KEY,JSON.stringify(store));$("#saveStatus").textContent="Saved on this device"},160)};
  const message=t=>!t.planned?"Add planned expenses to see how the month is shaping up.":t.plannedBalance<0?`Your plan is ${money.format(Math.abs(t.plannedBalance))} above income. Reduce planned spending before the month begins.`:t.spentRate>100?`Actual spending is ${money.format(t.actual-t.planned)} over budget. Review the categories marked in red.`:t.spentRate>=80?`You have used ${Math.round(t.spentRate)}% of the expense budget, with ${money.format(t.remaining)} of income remaining.`:`The plan leaves ${money.format(t.plannedBalance)} unassigned. Actual spending is ${Math.round(t.spentRate)}% of the expense budget.`;
  const pacing=b=>{const[y,m]=store.activeMonth.split("-").map(Number),totalDays=new Date(y,m,0).getDate(),current=now(),elapsed=store.activeMonth<current?totalDays:store.activeMonth>current?0:Math.min(new Date().getDate(),totalDays),daysRemaining=Math.max(0,totalDays-elapsed),groups=b.categories.map(c=>({...catTotals(c),type:c.type})),flexibleBudget=groups.filter(g=>g.type==="flexible").reduce((s,g)=>s+g.planned,0),flexibleActual=groups.filter(g=>g.type==="flexible").reduce((s,g)=>s+g.actual,0),fixedExpected=groups.filter(g=>g.type==="fixed").reduce((s,g)=>s+Math.max(g.planned,g.actual),0),flexibleLeft=flexibleBudget-flexibleActual,spendPct=flexibleBudget?flexibleActual/flexibleBudget*100:0,elapsedPct=elapsed/totalDays*100,projectedFlexible=elapsed>0&&elapsed<totalDays?flexibleActual/elapsed*totalDays:flexibleActual;return{daysRemaining,flexibleBudget,flexibleLeft,spendPct,elapsedPct,projectedBalance:b.income-fixedExpected-projectedFlexible,daily:daysRemaining?Math.max(0,flexibleLeft)/daysRemaining:0,isCurrent:store.activeMonth===current}};
  const renderSummary=()=>{const b=active(),t=totals(b),p=pacing(b),cap=Math.min(100,Math.max(0,t.spentRate));$("#incomeSummary").textContent=money.format(b.income);$("#budgetSummary").textContent=money.format(t.planned);$("#actualSummary").textContent=money.format(t.actual);$("#remainingSummary").textContent=money.format(t.remaining);$("#plannedSummary").textContent=money.format(t.plannedBalance);$("#remainingCard").classList.toggle("negative",t.remaining<0);$("#spentPercent").textContent=`${Math.round(t.spentRate)}%`;$("#budgetInsight").textContent=message(t);$("#budgetDonut").style.setProperty("--spent",`${cap*3.6}deg`);$("#budgetDonut").setAttribute("aria-label",`${Math.round(t.spentRate)} percent of the expense budget spent`);$("#overallProgress").style.width=`${cap}%`;$("#daysRemaining").textContent=p.daysRemaining;$("#flexibleRemaining").textContent=money.format(p.flexibleLeft);$("#safeDaily").textContent=money.format(p.daily);$("#projectedBalance").textContent=money.format(p.projectedBalance);$("#projectedBalance").parentElement.classList.toggle("negative",p.projectedBalance<0);$("#flexibleRemaining").parentElement.classList.toggle("negative",p.flexibleLeft<0);$("#paceFill").style.width=`${Math.min(100,p.spendPct)}%`;$("#paceMarker").style.left=`${Math.min(100,p.elapsedPct)}%`;$("#paceTrack").setAttribute("aria-valuenow",String(Math.round(Math.min(100,p.spendPct))));$("#paceStatus").textContent=!p.flexibleBudget?"Mark at least one category as flexible to calculate spending pace.":!p.isCurrent?"Pacing is shown against this month's full calendar.":p.spendPct>p.elapsedPct+5?`Flexible spending is ${Math.round(p.spendPct-p.elapsedPct)} points ahead of the calendar.`:p.spendPct<p.elapsedPct-5?`Flexible spending is ${Math.round(p.elapsedPct-p.spendPct)} points behind the calendar.`:"Flexible spending is closely aligned with the calendar.";$("#srAnnouncer").textContent=`Budget summary updated. ${money.format(t.remaining)} remains after actual spending. Safe daily flexible spending is ${money.format(p.daily)}.`};
  const render=()=>{const b=active();$("#budgetMonth").value=store.activeMonth;$("#periodHeading").textContent=label(store.activeMonth);$("#netIncome").value=b.income;const list=$("#categoryList");list.replaceChildren();b.categories.forEach(c=>{const card=$("#categoryTemplate").content.firstElementChild.cloneNode(true);card.dataset.id=c.id;$(".category-name",card).value=c.name;$(".category-type",card).value=c.type;const t=catTotals(c),variance=t.planned-t.actual,rate=t.planned?t.actual/t.planned*100:0;$(".category-budget",card).textContent=money.format(t.planned);$(".category-actual",card).textContent=money.format(t.actual);const v=$(".category-variance",card);v.textContent=variance>=0?`${money.format(variance)} left`:`${money.format(Math.abs(variance))} over`;v.classList.toggle("over",variance<0);const bar=$(".category-progress span",card);bar.style.width=`${Math.min(100,rate)}%`;bar.classList.toggle("over",rate>100);const items=$(".items",card);c.items.forEach(i=>{const row=$("#itemTemplate").content.firstElementChild.cloneNode(true);row.dataset.id=i.id;$(".item-name",row).value=i.name;$(".item-budget",row).value=i.budget;$(".item-actual",row).value=i.actual;items.append(row)});list.append(card)});renderSummary()};
  const findCat=e=>active().categories.find(c=>c.id===e.closest(".category-card")?.dataset.id),findItem=(e,c)=>c?.items.find(i=>i.id===e.closest(".item-row")?.dataset.id);
  $("#budgetMonth").addEventListener("change",e=>{const m=e.target.value||now();if(!store.months[m])store.months[m]={month:m,income:0,categories:[]};store.activeMonth=m;render();save()});
  $("#copyMonthButton").addEventListener("click",()=>{const months=Object.keys(store.months).filter(m=>m<store.activeMonth).sort(),source=store.months[months.at(-1)];if(!source)return alert("There is no earlier saved month to copy.");store.months[store.activeMonth]=clone(source,store.activeMonth);render();save()});
  $("#netIncome").addEventListener("input",e=>{active().income=amount(e.target.value);renderSummary();save()});
  $("#categoryList").addEventListener("input",e=>{const c=findCat(e.target);if(!c)return;if(e.target.matches(".category-name"))c.name=e.target.value;const i=findItem(e.target,c);if(i&&e.target.matches(".item-name"))i.name=e.target.value;if(i&&e.target.matches(".item-budget"))i.budget=amount(e.target.value);if(i&&e.target.matches(".item-actual"))i.actual=amount(e.target.value);if(e.target.matches(".item-budget,.item-actual"))renderSummary();save()});
  $("#categoryList").addEventListener("change",e=>{const c=findCat(e.target);if(!c)return;if(e.target.matches(".category-type"))c.type=e.target.value==="fixed"?"fixed":"flexible";render();save()});
  $("#categoryList").addEventListener("click",e=>{const c=findCat(e.target);if(!c)return;if(e.target.closest(".add-item"))c.items.push({id:uid(),name:"New expense",budget:0,actual:0});else if(e.target.closest(".remove-item")){const i=findItem(e.target,c);c.items=c.items.filter(x=>x.id!==i?.id)}else if(e.target.closest(".remove-category"))active().categories=active().categories.filter(x=>x.id!==c.id);else return;render();save()});
  $("#categoryList").addEventListener("keydown",e=>{if(!e.target.matches(".item-budget,.item-actual"))return;const selector=e.target.matches(".item-budget")?".item-budget":".item-actual",column=$$(selector),all=$$(".item-budget,.item-actual"),i=column.indexOf(e.target),j=all.indexOf(e.target),next=e.key==="ArrowDown"?column[i+1]:e.key==="ArrowUp"?column[i-1]:e.key==="Enter"?all[j+1]:null;if(next){e.preventDefault();next.focus();next.select()}});
  $("#addCategoryButton").addEventListener("click",()=>{active().categories.push({id:uid(),name:"New category",type:"flexible",items:[{id:uid(),name:"New expense",budget:0,actual:0}]});render();save();$$(".category-name").at(-1)?.focus()});
  const download=(content,type,name)=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
  $("#exportButton").addEventListener("click",()=>download(JSON.stringify(store,null,2),"application/json","soma-budget-backup.json"));
  $("#csvButton").addEventListener("click",()=>{const rows=[["Month","Type","Category","Item","Budget","Actual"]];Object.entries(store.months).sort().forEach(([m,b])=>b.categories.forEach(c=>c.items.forEach(i=>rows.push([m,c.type,c.name,i.name,i.budget,i.actual]))));download(rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv","soma-budget-history.csv")});
  $("#importButton").addEventListener("click",()=>$("#importFile").click());
  $("#importFile").addEventListener("change",async e=>{const[file]=e.target.files;if(!file)return;try{if(file.size>2_000_000)throw Error();const data=JSON.parse(await file.text());if(data?.version===2)store=normalize(data);else if(data?.categories){const b=clean(data);store={version:2,activeMonth:b.month,months:{[b.month]:b}}}else throw Error();localStorage.setItem(KEY,JSON.stringify(store));render();$("#saveStatus").textContent="Backup imported"}catch{alert("That file is not a valid SOMA Budget Planner backup.")}e.target.value=""});
  $("#printButton").addEventListener("click",()=>print());$("#resetButton").addEventListener("click",()=>$("#confirmDialog").showModal());$("#confirmDialog").addEventListener("close",e=>{if(e.target.returnValue==="confirm"){store.months[store.activeMonth]=sample(store.activeMonth);render();save()}});
  const applyTheme=theme=>{document.documentElement.dataset.theme=theme;$("#themeButton").textContent=theme==="dark"?"Light mode":"Dark mode";$("#themeButton").setAttribute("aria-pressed",String(theme==="dark"));$('meta[name="theme-color"]').content=theme==="dark"?"#0c1016":"#0f766e"};
  applyTheme(localStorage.getItem(THEME_KEY)==="dark"?"dark":"light");$("#themeButton").addEventListener("click",()=>{const theme=document.documentElement.dataset.theme==="dark"?"light":"dark";localStorage.setItem(THEME_KEY,theme);applyTheme(theme)});
  render();localStorage.setItem(KEY,JSON.stringify(store));if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("service-worker.js",{updateViaCache:"none"}).then(registration=>registration.update());
})();
