(() => {
  "use strict";
  const KEY="soma-budget-planner-v2", OLD="soma-budget-planner-v1";
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
  const now=()=>new Date().toISOString().slice(0,7), uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
  const amount=v=>Math.max(0,Number.isFinite(Number(v))?Number(v):0);
  const label=m=>new Intl.DateTimeFormat("en-US",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${m}-01T00:00:00Z`));
  const sample=(month=now())=>({month,income:8500,categories:[
    {id:uid(),name:"Housing",items:[{id:uid(),name:"Rent (SOMA 1BR)",budget:3500,actual:3500},{id:uid(),name:"Renter's Insurance",budget:25,actual:25}]},
    {id:uid(),name:"Utilities",items:[{id:uid(),name:"PG&E",budget:120,actual:0},{id:uid(),name:"Internet & Phone",budget:165,actual:0},{id:uid(),name:"Water & Garbage",budget:60,actual:0}]},
    {id:uid(),name:"Food & Pet Care",items:[{id:uid(),name:"Groceries",budget:450,actual:0},{id:uid(),name:"Dining Out & Coffee",budget:350,actual:0},{id:uid(),name:"Pet Care (Diggy)",budget:100,actual:0}]},
    {id:uid(),name:"Lifestyle & Transit",items:[{id:uid(),name:"Entertainment & Nightlife",budget:300,actual:0},{id:uid(),name:"Transit & Rideshare",budget:150,actual:0},{id:uid(),name:"Subscriptions",budget:100,actual:0}]}
  ]});
  const clean=(b,month=now())=>({month:/^\d{4}-\d{2}$/.test(b?.month||"")?b.month:month,income:amount(b?.income),categories:Array.isArray(b?.categories)?b.categories.map(c=>({id:String(c.id||uid()),name:String(c.name||"Untitled category").slice(0,50),items:Array.isArray(c.items)?c.items.map(i=>({id:String(i.id||uid()),name:String(i.name||"Untitled item").slice(0,70),budget:amount(i.budget),actual:amount(i.actual)})):[]})):[]});
  const clone=(b,month)=>({month,income:b.income,categories:b.categories.map(c=>({id:uid(),name:c.name,items:c.items.map(i=>({id:uid(),name:i.name,budget:i.budget,actual:0}))}))});
  const load=()=>{try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.version===2&&s.months){const months=Object.fromEntries(Object.entries(s.months).map(([k,v])=>[k,clean(v,k)]));const activeMonth=months[s.activeMonth]?s.activeMonth:Object.keys(months)[0]||now();if(!months[activeMonth])months[activeMonth]=sample(activeMonth);return{version:2,activeMonth,months}}}catch{}try{const old=JSON.parse(localStorage.getItem(OLD));if(old?.categories){const b=clean(old);return{version:2,activeMonth:b.month,months:{[b.month]:b}}}}catch{}const b=sample();return{version:2,activeMonth:b.month,months:{[b.month]:b}}};
  let store=load(), timer; const active=()=>store.months[store.activeMonth];
  const totals=(b=active())=>{const items=b.categories.flatMap(c=>c.items),planned=items.reduce((s,i)=>s+amount(i.budget),0),actual=items.reduce((s,i)=>s+amount(i.actual),0);return{planned,actual,remaining:b.income-actual,plannedBalance:b.income-planned,spentRate:planned?actual/planned*100:0}};
  const catTotals=c=>({planned:c.items.reduce((s,i)=>s+amount(i.budget),0),actual:c.items.reduce((s,i)=>s+amount(i.actual),0)});
  const save=()=>{$("#saveStatus").textContent="Saving...";clearTimeout(timer);timer=setTimeout(()=>{localStorage.setItem(KEY,JSON.stringify(store));$("#saveStatus").textContent="Saved on this device"},160)};
  const message=t=>!t.planned?"Add planned expenses to see how the month is shaping up.":t.plannedBalance<0?`Your plan is ${money.format(Math.abs(t.plannedBalance))} above income. Reduce planned spending before the month begins.`:t.spentRate>100?`Actual spending is ${money.format(t.actual-t.planned)} over budget. Review the categories marked in red.`:t.spentRate>=80?`You have used ${Math.round(t.spentRate)}% of the expense budget, with ${money.format(t.remaining)} of income remaining.`:`The plan leaves ${money.format(t.plannedBalance)} unassigned. Actual spending is ${Math.round(t.spentRate)}% of the expense budget.`;
  const renderSummary=()=>{const b=active(),t=totals(b),cap=Math.min(100,Math.max(0,t.spentRate));$("#incomeSummary").textContent=money.format(b.income);$("#budgetSummary").textContent=money.format(t.planned);$("#actualSummary").textContent=money.format(t.actual);$("#remainingSummary").textContent=money.format(t.remaining);$("#plannedSummary").textContent=money.format(t.plannedBalance);$("#remainingCard").classList.toggle("negative",t.remaining<0);$("#spentPercent").textContent=`${Math.round(t.spentRate)}%`;$("#budgetInsight").textContent=message(t);$("#budgetDonut").style.setProperty("--spent",`${cap*3.6}deg`);$("#overallProgress").style.width=`${cap}%`};
  const render=()=>{const b=active();$("#budgetMonth").value=store.activeMonth;$("#periodHeading").textContent=label(store.activeMonth);$("#netIncome").value=b.income;const list=$("#categoryList");list.replaceChildren();b.categories.forEach(c=>{const card=$("#categoryTemplate").content.firstElementChild.cloneNode(true);card.dataset.id=c.id;$(".category-name",card).value=c.name;const t=catTotals(c),variance=t.planned-t.actual,rate=t.planned?t.actual/t.planned*100:0;$(".category-budget",card).textContent=money.format(t.planned);$(".category-actual",card).textContent=money.format(t.actual);const v=$(".category-variance",card);v.textContent=variance>=0?`${money.format(variance)} left`:`${money.format(Math.abs(variance))} over`;v.classList.toggle("over",variance<0);const bar=$(".category-progress span",card);bar.style.width=`${Math.min(100,rate)}%`;bar.classList.toggle("over",rate>100);const items=$(".items",card);c.items.forEach(i=>{const row=$("#itemTemplate").content.firstElementChild.cloneNode(true);row.dataset.id=i.id;$(".item-name",row).value=i.name;$(".item-budget",row).value=i.budget;$(".item-actual",row).value=i.actual;items.append(row)});list.append(card)});renderSummary()};
  const findCat=e=>active().categories.find(c=>c.id===e.closest(".category-card")?.dataset.id),findItem=(e,c)=>c?.items.find(i=>i.id===e.closest(".item-row")?.dataset.id);
  $("#budgetMonth").addEventListener("change",e=>{const m=e.target.value||now();if(!store.months[m])store.months[m]={month:m,income:0,categories:[]};store.activeMonth=m;render();save()});
  $("#copyMonthButton").addEventListener("click",()=>{const months=Object.keys(store.months).filter(m=>m<store.activeMonth).sort(),source=store.months[months.at(-1)];if(!source)return alert("There is no earlier saved month to copy.");store.months[store.activeMonth]=clone(source,store.activeMonth);render();save()});
  $("#netIncome").addEventListener("input",e=>{active().income=amount(e.target.value);renderSummary();save()});
  $("#categoryList").addEventListener("input",e=>{const c=findCat(e.target);if(!c)return;if(e.target.matches(".category-name"))c.name=e.target.value;const i=findItem(e.target,c);if(i&&e.target.matches(".item-name"))i.name=e.target.value;if(i&&e.target.matches(".item-budget"))i.budget=amount(e.target.value);if(i&&e.target.matches(".item-actual"))i.actual=amount(e.target.value);render();save()});
  $("#categoryList").addEventListener("click",e=>{const c=findCat(e.target);if(!c)return;if(e.target.closest(".add-item"))c.items.push({id:uid(),name:"New expense",budget:0,actual:0});else if(e.target.closest(".remove-item")){const i=findItem(e.target,c);c.items=c.items.filter(x=>x.id!==i?.id)}else if(e.target.closest(".remove-category"))active().categories=active().categories.filter(x=>x.id!==c.id);else return;render();save()});
  $("#addCategoryButton").addEventListener("click",()=>{active().categories.push({id:uid(),name:"New category",items:[{id:uid(),name:"New expense",budget:0,actual:0}]});render();save();$$(".category-name").at(-1)?.focus()});
  const download=(content,type,name)=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
  $("#exportButton").addEventListener("click",()=>download(JSON.stringify(store,null,2),"application/json","soma-budget-backup.json"));
  $("#csvButton").addEventListener("click",()=>{const rows=[["Month","Category","Item","Budget","Actual"]];Object.entries(store.months).sort().forEach(([m,b])=>b.categories.forEach(c=>c.items.forEach(i=>rows.push([m,c.name,i.name,i.budget,i.actual]))));download(rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv","soma-budget-history.csv")});
  $("#importButton").addEventListener("click",()=>$("#importFile").click());$("#importFile").addEventListener("change",async e=>{const[file]=e.target.files;if(!file)return;try{const data=JSON.parse(await file.text());if(data?.version===2&&data.months)localStorage.setItem(KEY,JSON.stringify(data));else if(data?.categories)localStorage.setItem(OLD,JSON.stringify(data));else throw Error();store=load();render();save()}catch{alert("That file is not a valid SOMA Budget Planner backup.")}e.target.value=""});
  $("#printButton").addEventListener("click",()=>print());$("#resetButton").addEventListener("click",()=>$("#confirmDialog").showModal());$("#confirmDialog").addEventListener("close",e=>{if(e.target.returnValue==="confirm"){store.months[store.activeMonth]=sample(store.activeMonth);render();save()}});
  render();localStorage.setItem(KEY,JSON.stringify(store));if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("service-worker.js");
})();
